# Generated by Django 4.1.4 on 2023-03-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='lastname',
        ),
    ]
